### ISSUE TITLE
Question about repository status

### ISSUE THREAD

**Issue by jmcnevin** [pborman/uuid#47]
I'm curious about about how this project is related to github.com/google/uuid.  It would appear that this is a fork of that project (or vice versa), and pborman seems to be an admin to that repo as well, but I'm not sure if one of these repos should be considered more "official" than the other.  Would anyone be able to offer some clarification?

**Comment by sethgrid** [comment]
My understanding was that it was his project and hosted there. I assumed some policy change required that he move it out of there. It looks like google might be making an "official" uuid package that is still experimental.

**Comment by pborman** [comment]
Sorry, I was changing jobs this spring/summer.  And yes, I am the author of both versions, and neither is going away.  The google one came much later and was the result of discussions about the benefits of using an array rather than a slice (an array is comparable) as well as a note from a lawyer (no legal issues, don't worry).  The result was I ended up copying the code into the google tree *and* changed from a byte slice to an array.

While I like having UUIDs being an array rather than a slice, this package (the slicer version), is more popular.  As of this spring it was also the most widely used inside of Google.  (I expect that is still true).  In hind sight I should have either not created the google one (see lawyer) or I should not have changed it to an array, in which case the packages would be identical.

The Array type in this package is compatible with the UUID type in the google package.

I will be updating this version to leverage the google version where appropriate, in particular, around the clock and node code.  This will reduce the amount of duplicated code a bit.
